#!/bin/bash
set -euo pipefail

main() {
  pbf=${1:?must provide path to pbf}
  pbf=$(readlink -f "$pbf")

  orig="$(readlink -f .)"

  me="$(readlink -f "$0")"
  here="$(dirname "$me")"
  cd "${here}"
  # Explicitly enumerate the things to export.
  # By convention, do them in alphabetical order, things prefixed with z are handled
  # last and may assume the existence of the previous exports, e.g. for use in
  # FindIntersecting calls.
  for candidate in city-parks.lua countries.lua parks.lua states.lua zindex.lua ztrails.lua; do
    candidate="$(basename "${candidate}" .lua)"

    cd "${orig}"
    "$here"/export "${pbf}" "${candidate}"
  done

}

main "$@"
