name: Build tilemaker exports

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AREA: north-america

    strategy:
      matrix:
        export: [
          city-parks,
          countries,
          parks,
          states
        ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: sudo apt install libboost-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libluajit-5.1-dev libshp-dev libsqlite3-dev rapidjson-dev zlib1g-dev luarocks lua-sql-sqlite3 && sudo luarocks install luaflock

      - name: Fetch binaries
        run: ./bin/fetch-binaries

      - name: Fetch PBF
        run: wget --progress=dot:giga https://public.hikeratlas.com/pbfs/$AREA.pbf

      - name: Export
        env:
          TILEMAKER: /tmp/tilemaker
          EXPORT: ${{ matrix.export }}
        run: ./export/export $AREA.pbf $EXPORT

      - name: Upload GeoJSON
        env:
          AWS_ENDPOINT_URL: https://ce5627cfc65c8b54d40bb91c0ba7298b.r2.cloudflarestorage.com
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FILE: ${{ matrix.export }}.geojsonl
        run: set -x; aws --version; zstd -9 $FILE && aws s3 cp "$FILE".zst s3://hikes-public/geojsonl/"$FILE".zst
